create table public.bookings (
  id bigint generated by default as identity primary key,
  event_type text not null,
  date_str text not null,
  guests text not null,
  name text not null,
  email text not null,
  phone text,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.bookings enable row level security;

create policy "Allow public inserts" on public.bookings
  for insert to anon, authenticated
  with check (true);

create policy "Allow authenticated full access" on public.bookings
  for all to authenticated
  using (true)
  with check (true);

create index if not exists idx_bookings_created_at on public.bookings(created_at);
create index if not exists idx_bookings_email on public.bookings(email);
